import { GetCreditRecievableElementModel } from "../creditReceivable/get-credit-recievable-element.model";
import { GetPaymentTransactionModel } from "../paymentTransaction/get-payment-transaction.model";

export interface GetCreditNoteModel {
  id: number;
  code: string;
  voucherName: string;
  customerName: string;
  customerCode: string;
  documentDate: string;
  refNumber: string;
  paymentOnlineRef: string;
  isPaidOnline: boolean;
  customerId: number;
  entityCode: string;
  salesRepresentativeId: string;
  arabicRemarks: string;
  englishRemarks: string;
  creditCardTypeId: string;
  discountCouponId: string;
  isBankDeposit: boolean;
  bankAccountId: string;
  qrCode: string;
  bankDepositAmount: number;
  isCashBox: boolean;
  isArchived: boolean;
  cashBoxId: string;
  cashBoxAmount: number;
  netValueAfterDiscount: number;
  taxAmount: number | null;
  netValueAfterTax: number | null;
  netValue: number;
  tolalPaid: number;
  totalRefund: number;
  sectorTypeId: string;
  branchId: string;
  isDownPayment: boolean;
  paymentsTransactions: GetPaymentTransactionModel[];
  costElements: GetCreditRecievableElementModel[];
}
